### ISSUE TITLE
Inflight page crash

### ISSUE THREAD

**Issue by Wertyuud** [chkr1011/mqttMultimeter#100]
I noticed that v1.9.0.290 sometimes crashes, when i select message in the inflight page. I attach below recording how to realibly crash app. Basicaly I send two messages (can be on the same topic), delete them in the inflight page, then send them again. Next I select first message in the inflight page, then select second, and app crashes. 
Environment: Windows 11, mosquitto 2.0.14

https://github.com/user-attachments/assets/f01979ee-9d22-4bf8-ab5d-7bff2fd8687d

**Comment by chkr1011** [comment]
This is caused by Avalonia and an internal race condition when changing the selection in the `DataGrid`.

I changed the details are so that it uses a `ContentPresenter` like all other pages. I was not able to reproduce the issue (yet).

Are able to build from the branch attached to this ticket and also test it as well?

**Comment by Wertyuud** [comment]
Thank you for quick response!
I checked out ```100-inflight-page-crash``` branch and and this specific issue seems to be fixed. However in the mean time I ran into similar problem when using topic explorer. It also causes app crash, and it's was bit more difficult to reproduce.  It's not fixed on this branch. Should I file new issue?

https://github.com/user-attachments/assets/ed9a3aa5-75e9-4be6-bc7e-e6c9f43a7edb

**Comment by chkr1011** [comment]
> Should I file new issue?

No there is no need to. I will also fix it in this branch because it probably has the same root cause.

**Comment by chkr1011** [comment]
@Wertyuud Ich also patched the Topic Explorer. Please let me know if it works better now.

**Comment by chkr1011** [comment]
I will now merge the PR so that a new version can be released soon.
