### ISSUE TITLE
Tree view

### ISSUE THREAD

**Issue by peterhoeg** [chkr1011/mqttMultimeter#65]
The "gold standard" for mqtt GUI clients (IMHO) is MQTT-Explorer which sadly is no longer actively maintained.

It has a tree-view as an alternative to the "inflight" panel in mqttnetapp, which is *very* useful.

It would be awesome to have something like this here as well.

![mqttexp](https://user-images.githubusercontent.com/722550/221773715-6552090c-b184-4797-9421-a5fd251e8aa2.png)

**Comment by chkr1011** [comment]
Please try the topic explorer tab on the left sidebar. It is exactly what you need.
