### ISSUE TITLE
the executable is so huge, is it possible slim it?

### ISSUE THREAD

**Issue by yurenchen000** [chkr1011/mqttMultimeter#68]
executable from v1.7.0.211 mqttMultimeter-linux-x64.zip 

`176M` 2023-04-30 10:22 mqttMultimeter

<br>

`file` says not stripped, but after `strip` it'll broken.

<br>

$ file ./mqttMultimeter
./mqttMultimeter: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=8c843397ceec509a72a2b2394d574f5822bb3aad, not stripped, too many notes (256)

$ strip  ./mqttMultimeter

$ ./mqttMultimeter 
Failure processing application bundle; possible file corruption.
Arithmetic overflow while reading bundle.
A fatal error occurred while processing application bundle

**Comment by chkr1011** [comment]
The file contains the entire .NET runtime and the required libraries like Avalonia, MQTTnet etc. There are ways to shrink the file by removing the not needed parts of the runtime but that did not work pretty well because too much references were removed.

**Comment by yurenchen000** [comment]
thanks for your explain.
that makes sense.

maybe it'll better if can manage depends like linux package mange  (but I never heard that things on .net)
never mind

**Comment by igloo15** [comment]
Its possible to build it without the runtime if you have the runtime already installed on the system. Maybe having a version of the exe that doesn't bundle the runtime would be an option for some.

**Comment by peterhoeg** [comment]
When building it on NixOS, we end up with the following for the application on its own:

```sh
$ du -hsc /nix/store/dmni8nljc5k1i7pb4krpb9cw4gjdr2mg-mqttmultimeter-1.7.0.211
87M     /nix/store/dmni8nljc5k1i7pb4krpb9cw4gjdr2mg-mqttmultimeter-1.7.0.211
```

Now if we take all transitive dependencies into consideration:
```sh
$ nix path-info -Sh /nix/store/dmni8nljc5k1i7pb4krpb9cw4gjdr2mg-mqttmultimeter-1.7.0.211
/nix/store/dmni8nljc5k1i7pb4krpb9cw4gjdr2mg-mqttmultimeter-1.7.0.211     259.8M
```

So the question is of course if it is worth the effort to save around 80MB (the difference between the application on its own and the distributed .zip) with all it entails in terms of testing, troubleshooting and new and interesting bugs as a consequence. If this was my project, I'd probably say no.

The other alternative is of course to approach the various distributions and have them package and distribute the application in which case *they* would take on the work of replacing dependencies and supporting it.

Here's the PR for NixOS: https://github.com/NixOS/nixpkgs/pull/234136

**Comment by peterhoeg** [comment]
And I have just merged it, so mqttmultimeter is now officially in the largest Linux distribution based on number of packages.

**Comment by chkr1011** [comment]
I will create a build which does not include the runtime. This will require the .NET runtime to be installed but will shrink the binaries are lot.

**Comment by chkr1011** [comment]
It turns out that there is no (huge) size benefit when compiling the application without the framework being part of the executable. The reason is that when compiling without a target framework the build system will put all native versions of the Avalonia dependencies to the output directory. Since the _SkiaSharp_ library is more than 9 mb in size, the actual folder will be around 90 mb in size just with all native variants of the library. This makes sense because the version can potentially run on every supported system.

But there is also good news: After migrating to .NET 8.0 the application is now 115 mb in size (including the .NET framework) which means it losts around 50 mb in size.
