### ISSUE TITLE
[Bug] When the authentication fails, the stacktrace window overlays the buttons

### ISSUE THREAD

**Issue by SeppPenner** [chkr1011/mqttMultimeter#75]
When the authentication fails and you open the stacktrace window (If the error is large), the stacktrace window overlays the "Copy to clipboard" and "Ok" buttons.

1. 
![grafik](https://github.com/chkr1011/mqttMultimeter/assets/9639361/db8bf3a5-7560-4c83-9a0a-fa73e816be9e)

2. 
![grafik](https://github.com/chkr1011/mqttMultimeter/assets/9639361/bdfa0c85-d4f0-417f-af79-92a219227896)

If you close the stacktrace window again, the buttons are displyed again.

Not really a big thing, but this could be a bit nicer, I guess :D

**Comment by chkr1011** [comment]
Thanks for reporting this. I fixed the layout by adding a tab control. Dealing min and max height of the stack traces turned out to be a little bit clunky. Let me know that you think about the solution.

**Comment by SeppPenner** [comment]
Do you have a pre-release or should I check it from the latest source?
