### ISSUE TITLE
cannot connect to AWS IoT with certificate

### ISSUE THREAD

**Issue by phachem** [chkr1011/mqttMultimeter#77]
When connecting to AWS Iot Core, the selected pfx certificate seems to not be used in the TLS options. When I made the following changes to set the cert and applicationProtocols, it started working:
MqttClientService.cs:

            clientOptionsBuilder.WithTls(o =>
            {
                o.SslProtocol = item.ServerOptions.SelectedTlsVersion.Value;
                o.IgnoreCertificateChainErrors = item.ServerOptions.IgnoreCertificateErrors;
                o.IgnoreCertificateRevocationErrors = item.ServerOptions.IgnoreCertificateErrors;
                o.CertificateValidationHandler = item.ServerOptions.IgnoreCertificateErrors ? _ => true : null;

                **if (!string.IsNullOrEmpty(item.SessionOptions.CertificatePath))
                {
                    X509Certificate2Collection certificates = new()
                    {
                        new X509Certificate2(item.SessionOptions.CertificatePath)
                    };

                    o.Certificates = certificates;
                    o.ApplicationProtocols = new List<SslApplicationProtocol>() { new("mqtt") };
                }**
            });

**Comment by chkr1011** [comment]
Thanks for reporting the issue, I will integrate the fix and release a new version soon.
