### ISSUE TITLE
Publish page mixes the messages order

### ISSUE THREAD

**Issue by Wertyuud** [chkr1011/mqttMultimeter#90]
I often experienced the bug in which publish page sends wrong message ( not one I clicked, but some other). I tried to make this bug reproducible, so I added 3 messages. One message is totally empty, and I think it may be important. Below are the examples to reproduce issue.
 
First case:
I try to send  second non empty message, but it says topic is empty. I think it tried to send first message which is indeed empty.
Then when I resubscribe to the topic, this for same reason change how publish tab works, but it still totally mixes the order of message.

https://github.com/chkr1011/mqttMultimeter/assets/6557983/4ce6699c-32fc-46e9-9cf0-194ac4489517

I attached below saved settings
Connections.json
`{
  "Connections": [
    {
      "AuthenticationMethod": "",
      "CertificatePassword": null,
      "CertificatePath": "",
      "ClientId": "mqttMultimeter-d678ccf6-301b-4114-809b-9eaa98071fd2",
      "Host": "localhost",
      "IgnoreCertificateErrors": false,
      "KeepAliveInterval": 10,
      "Name": "localhost",
      "Port": 1883,
      "ProtocolVersion": 4,
      "TlsVersion": 0,
      "Transport": 0,
      "UserName": ""
    },
    {
      "AuthenticationMethod": "",
      "CertificatePassword": null,
      "CertificatePath": "",
      "ClientId": "mqttMultimeter-1c0d6e17-5821-4325-84bb-f8658265332d",
      "Host": "broker.hivemq.com",
      "IgnoreCertificateErrors": false,
      "KeepAliveInterval": 10,
      "Name": "Hive MQ",
      "Port": 1883,
      "ProtocolVersion": 4,
      "TlsVersion": 0,
      "Transport": 0,
      "UserName": ""
    },
    {
      "AuthenticationMethod": "",
      "CertificatePassword": null,
      "CertificatePath": "",
      "ClientId": "mqttMultimeter-170b710b-eb18-4b90-8f85-a0db3e70efab",
      "Host": "test.mosquitto.org",
      "IgnoreCertificateErrors": false,
      "KeepAliveInterval": 10,
      "Name": "Mosquitto Test",
      "Port": 1883,
      "ProtocolVersion": 4,
      "TlsVersion": 0,
      "Transport": 0,
      "UserName": ""
    }
  ]
}
`
Publish.json
`{
  "Publishes": [
    {
      "ContentType": "",
      "MessageExpiryInterval": 0,
      "Name": "Untitled",
      "Payload": "",
      "PayloadFormatIndicator": 0,
      "QualityOfServiceLevel": 0,
      "ResponseTopic": "",
      "Retain": false,
      "SubscriptionIdentifier": 0,
      "Topic": "",
      "TopicAlias": 0,
      "UserProperties": [
        {
          "Name": "",
          "Value": ""
        }
      ]
    },
    {
      "ContentType": "",
      "MessageExpiryInterval": 0,
      "Name": "Untitled",
      "Payload": "message1",
      "PayloadFormatIndicator": 0,
      "QualityOfServiceLevel": 0,
      "ResponseTopic": "",
      "Retain": false,
      "SubscriptionIdentifier": 0,
      "Topic": "topic1",
      "TopicAlias": 0,
      "UserProperties": [
        {
          "Name": "",
          "Value": ""
        }
      ]
    },
    {
      "ContentType": "",
      "MessageExpiryInterval": 0,
      "Name": "Untitled",
      "Payload": "message2",
      "PayloadFormatIndicator": 0,
      "QualityOfServiceLevel": 0,
      "ResponseTopic": "",
      "Retain": false,
      "SubscriptionIdentifier": 0,
      "Topic": "topic2",
      "TopicAlias": 0,
      "UserProperties": [
        {
          "Name": "",
          "Value": ""
        }
      ]
    }
  ]
}
`
Subscriptions.json
`{
  "Subscriptions": [
    {
      "Name": "Untitled",
      "NoLocal": false,
      "QualityOfServiceLevel": 0,
      "RetainAsPublished": false,
      "RetainHandling": 0,
      "Topic": "#"
    }
  ]
}
`

Second:
There are only two messages and it still sends wrong one in the second try.

https://github.com/chkr1011/mqttMultimeter/assets/6557983/e8aa78db-2773-4618-9cff-49f3b9682120

Connections.json
`{
  "Connections": [
    {
      "AuthenticationMethod": "",
      "CertificatePassword": null,
      "CertificatePath": "",
      "ClientId": "mqttMultimeter-84039cad-6a86-4ef7-b573-680448473db4",
      "Host": "localhost",
      "IgnoreCertificateErrors": false,
      "KeepAliveInterval": 10,
      "Name": "localhost",
      "Port": 1883,
      "ProtocolVersion": 4,
      "TlsVersion": 0,
      "Transport": 0,
      "UserName": ""
    },
    {
      "AuthenticationMethod": "",
      "CertificatePassword": null,
      "CertificatePath": "",
      "ClientId": "mqttMultimeter-a532afbf-5683-4abd-971a-38972463b61a",
      "Host": "broker.hivemq.com",
      "IgnoreCertificateErrors": false,
      "KeepAliveInterval": 10,
      "Name": "Hive MQ",
      "Port": 1883,
      "ProtocolVersion": 4,
      "TlsVersion": 0,
      "Transport": 0,
      "UserName": ""
    },
    {
      "AuthenticationMethod": "",
      "CertificatePassword": null,
      "CertificatePath": "",
      "ClientId": "mqttMultimeter-39a36691-e6e0-44a4-a23f-afda2dab24d7",
      "Host": "test.mosquitto.org",
      "IgnoreCertificateErrors": false,
      "KeepAliveInterval": 10,
      "Name": "Mosquitto Test",
      "Port": 1883,
      "ProtocolVersion": 4,
      "TlsVersion": 0,
      "Transport": 0,
      "UserName": ""
    }
  ]
}`
Publish.json
`{
  "Publishes": [
    {
      "ContentType": "",
      "MessageExpiryInterval": 0,
      "Name": "Untitled",
      "Payload": "message1",
      "PayloadFormatIndicator": 0,
      "QualityOfServiceLevel": 0,
      "ResponseTopic": "",
      "Retain": false,
      "SubscriptionIdentifier": 0,
      "Topic": "topic1",
      "TopicAlias": 0,
      "UserProperties": [
        {
          "Name": "",
          "Value": ""
        }
      ]
    },
    {
      "ContentType": "",
      "MessageExpiryInterval": 0,
      "Name": "Untitled",
      "Payload": "message2",
      "PayloadFormatIndicator": 0,
      "QualityOfServiceLevel": 0,
      "ResponseTopic": "",
      "Retain": false,
      "SubscriptionIdentifier": 0,
      "Topic": "topic2",
      "TopicAlias": 0,
      "UserProperties": [
        {
          "Name": "",
          "Value": ""
        }
      ]
    }
  ]
}`
Subscriptions.json
`{
  "Subscriptions": [
    {
      "Name": "Untitled",
      "NoLocal": false,
      "QualityOfServiceLevel": 0,
      "RetainAsPublished": false,
      "RetainHandling": 0,
      "Topic": "#"
    }
  ]
}`

Version v1.8.2.272,  windows 11 22631, mosquitto 2.0.14.

I don't remember such bug when I was using [v1.7.0.211] previously.

**Comment by chkr1011** [comment]
Please add file content in ticket. I will not download any files to my PC.

**Comment by Wertyuud** [comment]
@chkr1011 Thank you for reply! You're right. I updated original post with file contents instead of .zip files.

**Comment by chkr1011** [comment]
To me it looks like that this is an issue in Avalonia. I will wait for version 11 and hopefully the issue is gone.

**Comment by wedgberto** [comment]
There are a few factors that lead to this bug. 

One is the combination of `CompiledBinding` and the `Mode=OneTime` of the `Command` of the Publish button in PublishItemView.axaml

https://github.com/chkr1011/mqttMultimeter/blob/6980cbccdbd102735eb399e9ad4f75a743e86386/Source/Pages/Publish/PublishItemView.axaml#L26

Remove `Mode=OneTime` and the button acts on the currently selected publish item rather than always acting on the first publish item in the list. 

However, this fix smelled so I investigated further and checked the difference between the Publish page and Connection page (where the connect button binding works correctly) and found that the Connection page does not use `CompiledBinding`s and can confirm that removing the `x:DataType="publish:PublishItemViewModel"` attribute from the UserControl element and converting all `CompiledBinding`s to `Binding` results in the publish button acting on the currently selected publish item whilst retaining `Mode=OneTime`.

This still seemed suspicious to me though because the OneTime binding modes in the connections page work properly.

It turns out that the publish page item view is hooked up to the publish page view differently to how the connection item view is hooked up to the connection page view:
https://github.com/chkr1011/mqttMultimeter/blob/6980cbccdbd102735eb399e9ad4f75a743e86386/Source/Pages/Connection/ConnectionPageView.axaml#L57-L59
vs
https://github.com/chkr1011/mqttMultimeter/blob/6980cbccdbd102735eb399e9ad4f75a743e86386/Source/Pages/Publish/PublishPageView.axaml#L58-L60

Bind the `PublishItemView` as the content of a `ContentPresenter` and the selected item applies to the item view correctly.

**Comment by chkr1011** [comment]
Ah great, I thought it was related to the Avalonia version...
